### ISSUE TITLE
C# .NET Core Port

### ISSUE THREAD

**Issue by kevc63** [fsprojects/ExcelFinancialFunctions#20]
Hello,

This is great work and that I would like to port it to C# as a .NET core project. Do you have any preference in what I should call the port and who should receive credit. I'm looking to port to C# for  learning purposes, and to use on my blog.

Thanks, Kevin

**Comment by sergey-tihon** [comment]
hi @kevc63, do not you want to add C# friendly API to this project and open PR with your changes?

**Comment by kevc63** [comment]
From looking at Issue #9 I'm not sure this is .NET Core compatible, and I had no luck trying to build it as that in VS 2017. I'm am not sure doing a PR and making an API will meet my needs.

**Comment by obegendi** [comment]
@sergey-tihon @kevc63 We were port this library to .net core. You can use our nuget package.
https://github.com/Hesapkurdu/hk-financial-functions

Please contribute as well. Thank you.

**Comment by jcoliz** [comment]
Hi, folks. I am cleaning up old issues. Please note that after recent changes, this library now runs on any implementation of .NET Standard 2.0. My personal recommendation is to use this library, not port it, because of the exhaustive amount of testing that has been put into it. That said, to answer the original question, please give credit to the original author  Luca Bolognese https://github.com/lucabol
