### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by dsyme** [fsprojects/ExcelFinancialFunctions#23]
Would anyone like to be a second maintainer on this project? Please let me know :)  

Also, is anyone able to do the work to simplify this to use .NET SDK project files?

**Comment by luajalla** [comment]
Hi @dsyme, 

I had a look at the project files conversion and started to upgrade it [here](https://github.com/luajalla/ExcelFinancialFunctions/tree/feature/netstandard), however setting up all the newest paket, fake & co turned out to be trickier than expected. 
What is a nice example of a project to check these? I haven't been following the changes for a long time and Scaffold seems to be not fully up-to-date.

Thanks,
Natallie

**Comment by jcoliz** [comment]
HI, folks, please see PR #28 for the change to .NET SDK project files (for library and nunit tests anyways)

**Comment by dsyme** [comment]
Welcome @jcoliz as a new maintainer!

**Comment by jcoliz** [comment]
Thanks. It appears that we can close this issue. 😁
